name: "Install Dependencies"
description: "Installs Node and npm dependencies"
runs:
    using: "composite"
    steps:
        - name: Use Node.js 16.14.2
          uses: actions/setup-node@v3
          with:
            node-version: 16.14.2
            cache: 'npm'
        - run: npm ci
          shell: bash
